apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        name: myapp
    spec:
      containers:
      - name: myapp
        image: myapp-21
        imagePullPolicy: Never
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
        ports:
          - name: http-8888
            containerPort: 8888
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /livenessProbe
            port: 7999
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readinessProbe
            port: 7999
            scheme: HTTP
          initialDelaySeconds: 20
          timeoutSeconds: 2
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
      terminationGracePeriodSeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  revisionHistoryLimit: 10
# hpa will auto scale not allowing full control. 
# ---
# apiVersion: autoscaling/v2
# kind: HorizontalPodAutoscaler
# metadata:
#   name: myapp
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: myapp
#   minReplicas: 1
#   maxReplicas: 6
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       target:
#         type: Utilization
#         averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
    name: myapp
  type: NodePort
  sessionAffinity: None
  ports:
    - name: http-8888
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 30171
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  ingressClassName: nginx
  rules:
  - host: host.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: myapp
            port: 
              number: 8888
