apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
        name: myapp
    spec:
      containers:
      - name: myapp
        image: myapp-2
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - name: http-8888
            containerPort: 8888
            protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: 7999
            scheme: HTTP
          initialDelaySeconds: 90
          timeoutSeconds: 2
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 7999
            scheme: HTTP
          initialDelaySeconds: 90
          timeoutSeconds: 2
          periodSeconds: 20
          successThreshold: 1
          failureThreshold: 3
      terminationGracePeriodSeconds: 45
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  revisionHistoryLimit: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp
  minReplicas: 6
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
    name: myapp
  type: ClusterIP
  sessionAffinity: None
  ports:
    - name: http-8888
      protocol: TCP
      port: 8888
      targetPort: 8888
  internalTrafficPolicy: Cluster

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: myapp
            port: 
              number: 8888
